language: ruby

sudo: false

cache: bundler

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby-19mode
  - rbx-2
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

before_script:
  - git config --local user.email "travis@travis.ci"
  - git config --local user.name "Travis CI"

script:
  - bundle exec rspec
  - bundle exec overcommit --run
